name: custom_components
description: "Custom components for Projects"
version: 1.0.0
homepage: https://github.com/wablevaibhav/custom_components

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  intl: ^0.19.0
  shimmer: ^3.0.0
  youtube_player_iframe: ^5.1.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/Poppins/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
